- .changeset/hip-frogs-exist.md
- README.md
- transforms/deprecated-stateless-component.js
adds documentation for false-positives in other `deprecate-*` transforms as well.
> Implement and document deprecated-stateless-component

- bin/types-react-codemod.cjs
- transforms/useCallback-implicit-any.js
Since all these changes are related to types, we don't need to run on untyped files.
We already had to special-case untyped files in `useCallback-implicit-any`. We would've needed the same special-case for `context-any`.
Let's just apply this special case consistently.
> Only run codemod on tsx? files

- .github/workflows/node.js.yml
Checking cache takes up to 2mins currently making up 90% of CI time.
Implies that we trust PRs from people with write access
> Only check Yarn cache on PRs from forks

- .changeset/tough-dolphins-teach.md
- transforms/utils/__tests__/parseSync.js
- transforms/utils/parseSync.js
Closes https://github.com/eps1lon/types-react-codemod/issues/45
> fix: Parse .ts files without JSX plugin

- .github/workflows/node.js.yml
Seems like 18 is supported by Jest 28. [Prior failures](https://github.com/eps1lon/types-react-codemod/runs/6152638389?check_suite_focus=true) (https://github.com/eps1lon/types-react-codemod/pull/27) happened with jest 27
> Test with Node.js 18

- .changeset/smart-lamps-type.md
- bin/types-react-codemod.cjs
- transforms/context-any.js
- transforms/deprecated-react-child.js
- transforms/deprecated-react-text.js
- transforms/deprecated-react-type.js
- transforms/deprecated-sfc-element.js
- transforms/deprecated-sfc.js
- transforms/deprecated-stateless-component.js
- transforms/deprecated-void-function-component.js
- transforms/implicit-children.js
- transforms/preset-18.js
- transforms/preset-19.js
- transforms/useCallback-implicit-any.js
Closes https://github.com/eps1lon/types-react-codemod/issues/62
Previously jscodeshift would transpile the transforms before using them.
This was largely unnecessary and resulted in bugs to to usage of undeclared Babel dependencies.
Tested it by running the bin without the `module.exports` and it failed as expected since it needs the files as CommonJS. Previously jscodeshift transpiled the transforms so we didn't catch this problem.
> feat: Avoid transpiling transforms

- .changeset/strange-news-smoke.md
- .eslintrc.js
- babel.config.js
- bin/__tests__/types-react-codemod.js
- jest.config.js
- package.json
- transforms/__tests__/context-any.js
- transforms/__tests__/deprecated-react-child.js
- transforms/__tests__/deprecated-react-text.js
- transforms/__tests__/deprecated-react-type.js
- transforms/__tests__/deprecated-sfc-element.js
- transforms/__tests__/deprecated-sfc.js
- transforms/__tests__/deprecated-stateless-component.js
- transforms/__tests__/deprecated-void-function-component.js
- transforms/__tests__/implicit-children.js
- transforms/__tests__/preset-18.js
- transforms/__tests__/preset-19.js
- transforms/__tests__/useCallback-implicit-any.js
- transforms/preset-18.js
- transforms/preset-19.js
- transforms/utils/__tests__/parseSync.js
- yarn.lock
> fix: Don't use import statement

- .changeset/heavy-rockets-guess.md
- transforms/utils/__tests__/parseSync.js
Closes #91
They were probably pulling in an older version of Babel. This PR just adds a test for behavior fixed in Babel 7.18 (bumped in https://github.com/eps1lon/types-react-codemod/pull/67). This way we get a release with the (already) bumped version of Babel
> feat: Ensure TypeScript instantiation expressions can be parsed

- .changeset/selfish-candles-hide.md
- .github/workflows/node.js.yml
- README.md
- package.json
Node 14 was required implicitly but with https://github.com/eps1lon/types-react-codemod/pull/84 we'll definitely fail module evaluation (due to usage of `import()`) when used with Node.js 12 and no experimental modules flag.
> feat: Make supported Node.js version explicit

- .github/renovate.json
- .github/workflows/node.js.yml
- package.json
Not sure if Renovate supports dedupe with Yarn v2+. `yarn-deduplicate` doesn't work with v2+ so Renovate would have to use `yarn dedupe` instead.
> chore: Dedupe deps on auto updates

- .github/renovate.json
Seeing ["yarn dedupe fewer not available" in Renovate logs](https://app.renovatebot.com/dashboard#github/eps1lon/types-react-codemod/950470529) which makes sense since [Yarn v2+ only has "highest" as a strategy](https://yarnpkg.com/cli/dedupe).
> chore: Switch to "highest" strategy with `yarn dedupe`

- package.json
Pins `renovate-config-validator` to the version prior to https://github.com/renovatebot/renovate/pull/13416 which broke usage in Node.js 14.x (`??=` is not supported syntax in Node.js 14.x).
> Fix renovate validator failing in Node 14.x

- yarn.lock
Fixes https://github.com/eps1lon/types-react-codemod/actions/runs/4524470554/jobs/7968326212
```
Post-resolution validation
➤ YN0000: │ @@ -7012,13 +7012,12 @@
➤ YN0000: │    linkType: hard
➤ YN0000: │  
➤ YN0000: │  "typescript@patch:typescript@^5.0.0#~builtin<compat/typescript>":
➤ YN0000: │    version: 5.0.2
➤ YN0028: │ -  resolution: "typescript@patch:typescript@npm%3A5.0.2#~builtin<compat/typescript>::version=5.0.2&hash=1f5320"
➤ YN0028: │ +  resolution: "typescript@patch:typescript@npm%3A5.0.2#~builtin<compat/typescript>::version=5.0.2&hash=85af82"
➤ YN0000: │    bin:
➤ YN0000: │      tsc: bin/tsc
➤ YN0000: │      tsserver: bin/tsserver
➤ YN0028: │ -  checksum: bdbf3d0aac0d6cf0[10](https://github.com/eps1lon/types-react-codemod/actions/runs/4524470554/jobs/7968326212#step:4:12)fbe053 …
```
> Fix install in CI

- .github/workflows/node.js.yml
Otherwise you can't tell whether a failure is caused by a specific Node.js version or not.
> test: Don't fail all jobs if single test matrix entry fails

- .changeset/fifty-cheetahs-dance.md
- .changeset/kind-bugs-teach.md
`experimental-useRef-required-initial` was never released so no need to mention it in the changelog
> docs:  Squash changesets

- .changeset/short-zoos-type.md
- transforms/__tests__/deprecated-react-child.js
- transforms/__tests__/deprecated-react-fragment.js
- transforms/__tests__/deprecated-react-node-array.js
- transforms/__tests__/deprecated-react-text.js
- transforms/__tests__/scoped-jsx.js
- transforms/deprecated-react-child.js
- transforms/deprecated-react-fragment.js
- transforms/deprecated-react-node-array.js
- transforms/deprecated-react-text.js
- transforms/scoped-jsx.js
- transforms/utils/jscodeshift-bugfixes.js
Annoying bug in ast-types/recast?
> fix: Find and replace type usage in type parameters of call expressions

- .changeset/changelog.js
- .changeset/config.json
- tsconfig.json
Before: #1 abcdef0 Thanks @eps1lon! - This is a summary
After: This is a summary (#1 abcdef0 by @eps1lon!)
- `yarn changeset version` with `GITHUB_TOKEN` set as instructed when it's not set. Then just check `CHANGELOG.md` if that's intended, it is.
> Move PR, commit and author to end of changelog entry

- .changeset/thick-snakes-float.md
- README.md
- bin/__tests__/types-react-codemod.js
- bin/types-react-codemod.cjs
- transforms/__tests__/no-implicit-ref-callback-return.js
- transforms/__tests__/preset-19.js
- transforms/no-implicit-ref-callback-return.js
- transforms/preset-19.js
Closes https://github.com/eps1lon/types-react-codemod/issues/368
> feat: Add no-implicit-ref-callback-return transform

- .changeset/bright-trains-end.md
- README.md
- bin/__tests__/types-react-codemod.js
- bin/types-react-codemod.cjs
- transforms/__tests__/react-element-default-any-props.js
- transforms/preset-19.js
- transforms/react-element-default-any-props.js
Closes https://github.com/eps1lon/types-react-codemod/issues/367
Tested on vercel/nextjs and it's too broad. Added an extra caution message to clarify that you should rarely need this codemod.
> feat: Add react-element-default-any-props codemod

- .changeset/fifty-schools-shout.md
- package.json
- yarn.lock
Seeing error with yarn running the codemod
```
Require stack:
- /private/var/folders/gy/kq4zjn8s0ljf9sfjyyh_nj640000gn/T/xfs-7876c1ec/dlx-47763/.yarn/cache/types-react-codemod-npm-3.4.0-ab138b8b9f-7732b43362.zip/node_modules/types-react-c
odemod/transforms/refobject-defaults.js
- /private/var/folders/gy/kq4zjn8s0ljf9sfjyyh_nj640000gn/T/xfs-7876c1ec/dlx-47763/.yarn/cache/types-react-codemod-npm-3.4.0-ab138b8b9f-7732b43362.zip/node_modules/types-react-c
odemod/transforms/preset-19./private/var/folders/gy/kq4zjn8s0ljf9sfjyyh_nj640000gn/T/xfs-7876c1ec/dlx-47763/.pnp.cjs:9375
Error.captureStackTrace(firstError);
^
Error: types-react-codemod tried to access @babel/types, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: @babel/types …
```
> fix: missing dependencies for pnpx

- .changeset/sharp-dancers-breathe.md
- transforms/__tests__/deprecated-react-node-array.js
- transforms/utils/replaceType.js
This fixes an edge case we ran into where `ReactNodeArray` was being imported from `'prop-types'` but still being modified. The fix is to consider whether a named import exists when looking for references to that import. I'm aware that `prop-types` are going away in React 19 but I was modifying a React 18 codebase for forwards compatibility.
This fix also caught a typo with the `"in type parameters"` test.
> fix(replaceType): avoid modifying import not from 'react'

- .changeset/wise-icons-wash.md
- transforms/__tests__/deprecated-react-child.js
- transforms/utils/replaceType.js
This PR fixes an issue that we encountered running the React 19 codemods that would result in incorrect types like:
```diff
- children?: ReactChild[];
+ children?: ReactElement | number | string[];
```
I'm not sure if it's actually a bug in the recast printer but I think the solution here makes sense. We check if the parent is a `TSArrayType` and add parenthesis add a `TSParenthesizedType` wrapper if appropriate.
> fix(replaceType): handle array syntax

- .changeset/olive-suns-crash.md
- transforms/__tests__/scoped-jsx.js
- transforms/scoped-jsx.js
This fixes a limitation we ran into with the `scoped-jsx` codemod. There were a couple places that were importing `{ JSX } from 'react/jsx-runtime'` but the new `react` import was still being added. I assume that that code should just be importing from `'react'` to begin with but just wanted to push the PR in case it ends up being a common issue.
> fix(scoped-jsx): Don't add `JSX` import if `JSX` is already imported
